### ISSUE TITLE
Fairy in a bottle doesn't get removed when you are resurrected as stated

### ISSUE THREAD

**Issue by lilmike** [Difio3333/slaythetext#11]
Hiya,

I was lucky enough to get fairy in a bottle for one of my potions this run through, and found out, to my surprise, that it doesn't get removed when you get resurrected like it says in the description. This, um, well, leads to it being impossible for you to die. Lol. I just ran all the way up phase 3 with that bug, then ragequit when awakened one healed back to max, but y'know, that's just a detail. Lol.

Figured I'd let you know, since I'm not quite confident in the code enough to fix it myself yet.

-Michael.

**Comment by Difio3333** [comment]
:) That sounds fun but should be fixed now. I never legitimately made it to Act 3 myself in the text version so a cheat like that sounds handsome. Awakened One healing back to max is intended, though. That's its usual behaviour.
